<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BloodLink - Bangladesh</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
        .modal-blur {
            backdrop-filter: blur(8px);
        }

        .bg-medical {
            background-color: #FFF1F1;
        }
    </style>
</head>

<body class="bg-white font-sans text-gray-900">

    <!-- Header -->
    <header class="bg-white border-b sticky top-0 z-50">
        <div class="container mx-auto px-6 py-4 flex justify-between items-center">
            <div class="flex items-center gap-2">
                <div class="bg-red-600 p-2 rounded-lg">
                    <i class="fas fa-droplet text-white"></i>
                </div>
                <h1 class="text-xl font-bold tracking-tight">BloodLink</h1>
            </div>
            <button onclick="openModal('donorModal')"
                class="bg-red-600 text-white px-6 py-2 rounded-full text-sm font-bold hover:bg-red-700 transition">
                Become a Donor
            </button>
        </div>
    </header>

    <!-- Hero Section -->
    <section class="py-20 text-center">
        <div class="container mx-auto px-6">
            <div
                class="flex justify-center items-center gap-2 text-red-600 text-xs font-bold uppercase tracking-widest mb-6">
                <i class="fas fa-heart"></i> Save lives, one drop at a time
            </div>
            <h2 class="text-5xl md:text-6xl font-black mb-6 leading-tight">Find a <span class="text-red-600">blood
                    donor</span> in<br>seconds.</h2>
            <p class="text-gray-500 max-w-2xl mx-auto mb-12 text-lg">Search verified donors by blood group and district
                across Bangladesh. Reach them instantly when minutes matter most.</p>

            <!-- Search Bar -->
            <form action="{{ route('donors.index') }}" method="GET"
                class="bg-white shadow-2xl border border-gray-100 rounded-3xl p-3 max-w-3xl mx-auto flex flex-col md:flex-row gap-2 items-center">

                <div
                    class="flex-1 w-full flex items-center gap-3 px-4 py-3 border-b md:border-b-0 md:border-r border-gray-100">
                    <i class="fas fa-droplet text-red-500 opacity-50"></i>
                    <select name="blood_group"
                        class="w-full bg-transparent outline-none text-gray-600 font-medium cursor-pointer">
                        <option value="Any">Any blood group</option>
                        @foreach (['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'] as $group)
                            <option value="{{ $group }}"
                                {{ request('blood_group') == $group ? 'selected' : '' }}>{{ $group }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="flex-1 w-full flex items-center gap-3 px-4 py-3">
                    <i class="fas fa-location-dot text-red-500 opacity-50"></i>
                    <select name="district"
                        class="w-full bg-transparent outline-none text-gray-600 font-medium cursor-pointer">
                        <option value="Any">Any district</option>
                        @foreach (['Dhaka', 'Chattogram', 'Sylhet', 'Gazipur', 'Rajshahi', 'Khulna', 'Barishal', 'Rangpur', 'Mymensingh'] as $dist)
                            <option value="{{ $dist }}" {{ request('district') == $dist ? 'selected' : '' }}>
                                {{ $dist }}</option>
                        @endforeach
                    </select>
                </div>

                <button type="submit"
                    class="bg-red-600 text-white px-10 py-4 rounded-2xl font-bold hover:bg-red-700 transition w-full md:w-auto">
                    <i class="fas fa-search"></i> Search
                </button>
            </form>
        </div>
    </section>

    <!-- Blood Group Compatibility Grid -->
    <section class="py-12 bg-white">
        <div class="container mx-auto px-6">
            <h3 class="text-2xl font-bold mb-2">Blood group compatibility</h3>
            <p class="text-gray-400 text-sm mb-10 font-medium">Tap a card to see who can give and receive.</p>
            <div class="grid grid-cols-2 md:grid-cols-4 gap-6" id="bloodGrid">
                <!-- Cards Generated by JS -->
            </div>
        </div>
    </section>

    <!-- Available Donors -->
   <section class="py-20 bg-gray-50/50">
    <div id="donorContainer" class="grid grid-cols-1 md:grid-cols-2 gap-4">
        @forelse($donors as $donor)
            <div class="bg-white p-6 rounded-2xl border border-gray-100 flex items-center justify-between shadow-sm hover:shadow-md transition">
                <div class="flex items-center gap-4 text-left">
                    <div class="bg-red-600 text-white w-12 h-12 rounded-full flex items-center justify-center font-black text-sm shrink-0">
                        {{ $donor->blood_group }}
                    </div>
                    
                    <div>
                        <h4 class="font-bold text-gray-900">{{ $donor->name }}</h4>
                        <p class="text-[11px] text-gray-500 font-medium flex items-center gap-1">
                            <i class="fas fa-location-dot"></i> {{ $donor->location }}
                        </p>
                    </div>
                </div>
                
                <a href="tel:{{ $donor->phone }}" class="bg-red-600 text-white p-3 rounded-xl flex items-center gap-2 text-xs font-bold hover:bg-red-700">
                    <i class="fas fa-phone"></i>
                </a>
            </div>
        @empty
            <p class="col-span-full py-10 text-gray-400 text-center">No donors found.</p>
        @endforelse
    </div>
</section>

    <!-- Blood Facts -->
    <section class="py-20 container mx-auto px-6 text-center">
        <h3 class="text-2xl font-bold mb-2">Blood facts & donor health tips</h3>
        <p class="text-gray-400 text-sm mb-12">Know your impact. Stay healthy. Donate confidently.</p>

        <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
            @foreach ($facts as $fact)
                <div class="p-8 border border-gray-100 rounded-3xl text-left bg-white shadow-sm hover:shadow-md transition">
                <i class="{{$fact->icon}} text-red-500 mb-6 text-xl"></i>
                <h5 class="font-bold mb-3 text-sm">{{$fact->title}}</h5>
                <p class="text-xs text-gray-500 leading-relaxed">{{$fact->description}}</p>
            </div>
            @endforeach
        </div>
    </section>

    <!-- Emergency Button -->
    <button onclick="openModal('emergencyModal')"
        class="fixed bottom-8 right-8 bg-red-600 text-white px-6 py-3 rounded-full shadow-2xl font-bold flex items-center gap-3 hover:scale-105 transition-transform z-[40]">
        <i class="fas fa-hospital"></i> Emergency
    </button>

    <!-- ----------------- MODALS ----------------- -->

    <!-- Registration Modal -->
    <div id="donorModal" class="fixed inset-0 bg-black/40 hidden items-center justify-center z-[100] modal-blur p-4">
        <div class="bg-white rounded-[2.5rem] max-w-md w-full p-10 shadow-2xl relative">
            <button onclick="closeModal('donorModal')"
                class="absolute top-8 right-8 text-gray-300 hover:text-gray-500"><i
                    class="fas fa-times text-xl"></i></button>
            <h3 class="text-2xl font-bold mb-8">Become a donor</h3>

            <!-- Added action and method for backend compatibility -->
            <form action="{{ route('donor.store') }}" method="POST" class="space-y-5">
                @csrf
                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase mb-2 tracking-wide">Full name</label>
                    <div class="relative">
                        <span class="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400"><i
                                class="far fa-user text-sm"></i></span>
                        <input type="text" name="name" required placeholder="e.g. Tanvir Hossain"
                            class="w-full pl-11 pr-4 py-3.5 border border-gray-200 rounded-2xl focus:border-red-600 focus:ring-1 focus:ring-red-600 outline-none transition bg-white/50 placeholder:text-gray-400/80">
                    </div>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-5">
                    <div>
                        <label class="block text-xs font-bold text-gray-500 uppercase mb-2 tracking-wide">Date of
                            birth</label>
                        <div class="relative">
                            <span class="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400"><i
                                    class="far fa-calendar-alt text-sm"></i></span>
                            <input type="date" name="dob" required
                                class="w-full pl-11 pr-4 py-3.5 border border-gray-200 rounded-2xl focus:border-red-600 focus:ring-1 focus:ring-red-600 outline-none transition bg-white/50 text-gray-700">
                        </div>
                    </div>
                    <div>
                        <label class="block text-xs font-bold text-gray-500 uppercase mb-2 tracking-wide">Blood
                            group</label>
                        <div class="relative">
                            <span class="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400"><i
                                    class="fas fa-droplet text-sm"></i></span>
                            <select name="blood_group" required
                                class="w-full pl-11 pr-4 py-3.5 border border-gray-200 rounded-2xl focus:border-red-600 focus:ring-1 focus:ring-red-600 outline-none transition bg-white/50 text-gray-700 appearance-none">
                                <option value="" disabled selected>Select blood group</option>
                                <option>A+</option>
                                <option>A-</option>
                                <option>B+</option>
                                <option>B-</option>
                                <option>O+</option>
                                <option>O-</option>
                                <option>AB+</option>
                                <option>AB-</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-5">
                    <div>
                        <label class="block text-xs font-bold text-gray-500 uppercase mb-2 tracking-wide">Phone
                            number</label>
                        <div class="relative">
                            <span class="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400"><i
                                    class="fas fa-phone-alt text-sm"></i></span>
                            <input type="tel" name="phone" required placeholder="e.g. 01XXXXXXXXX"
                                class="w-full pl-11 pr-4 py-3.5 border border-gray-200 rounded-2xl focus:border-red-600 focus:ring-1 focus:ring-red-600 outline-none transition bg-white/50 placeholder:text-gray-400/80">
                        </div>
                    </div>
                    <div>
                        <label class="block text-xs font-bold text-gray-500 uppercase mb-2 tracking-wide">Weight
                            (kg)</label>
                        <div class="relative">
                            <span class="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400"><i
                                    class="fas fa-weight-scale text-sm"></i></span>
                            <input type="number" name="weight" required placeholder="e.g. 65" min="45"
                                class="w-full pl-11 pr-4 py-3.5 border border-gray-200 rounded-2xl focus:border-red-600 focus:ring-1 focus:ring-red-600 outline-none transition bg-white/50 placeholder:text-gray-400/80">
                        </div>
                    </div>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-5">
                    <div>
                        <label
                            class="block text-xs font-bold text-gray-500 uppercase mb-2 tracking-wide">District</label>
                        <div class="relative">
                            <span class="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400"><i
                                    class="fas fa-map-marker-alt text-sm"></i></span>
                            <select name="district" required
                                class="w-full pl-11 pr-4 py-3.5 border border-gray-200 rounded-2xl focus:border-red-600 focus:ring-1 focus:ring-red-600 outline-none transition bg-white/50 text-gray-700 appearance-none">
                                <option value="" disabled selected>Select district</option>
                                <option>Dhaka</option>
                                <option>Gazipur</option>
                                <option>Chattogram</option>
                                <option>Sylhet</option>
                                <option>Rajshahi</option>
                                <option>Khulna</option>
                                <option>Barishal</option>
                                <option>Rangpur</option>
                                <option>Mymensingh</option>
                            </select>
                        </div>
                    </div>
                    <div>
                        <label
                            class="block text-xs font-bold text-gray-500 uppercase mb-2 tracking-wide">Area/Location</label>
                        <div class="relative">
                            <span class="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400"><i
                                    class="fas fa-street-view text-sm"></i></span>
                            <input type="text" name="location" required placeholder="e.g. Mirpur"
                                class="w-full pl-11 pr-4 py-3.5 border border-gray-200 rounded-2xl focus:border-red-600 focus:ring-1 focus:ring-red-600 outline-none transition bg-white/50 placeholder:text-gray-400/80">
                        </div>
                    </div>
                </div>

                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase mb-2 tracking-wide">Last donation
                        date</label>
                    <div class="relative">
                        <span class="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400"><i
                                class="far fa-calendar-check text-sm"></i></span>
                        <input type="date" name="last_donation"
                            class="w-full pl-11 pr-4 py-3.5 border border-gray-200 rounded-2xl focus:border-red-600 focus:ring-1 focus:ring-red-600 outline-none transition bg-white/50 text-gray-700">
                    </div>
                    <p class="text-[10px] text-gray-400 mt-2 font-medium">* Leave blank if this is your first time.</p>
                </div>

                <div>
                    <label class="block text-xs font-bold text-gray-500 uppercase mb-2 tracking-wide">Email Address
                        (optional)</label>
                    <div class="relative">
                        <span class="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400"><i
                                class="far fa-envelope text-sm"></i></span>
                        <input type="email" name="email" placeholder="e.g. tanvir@example.com"
                            class="w-full pl-11 pr-4 py-3.5 border border-gray-200 rounded-2xl focus:border-red-600 focus:ring-1 focus:ring-red-600 outline-none transition bg-white/50 placeholder:text-gray-400/80">
                    </div>
                </div>

                <button type="submit"
                    class="w-full bg-red-600 text-white py-4 rounded-2xl font-black text-base hover:bg-red-700 transition duration-150 flex items-center justify-center gap-2 mt-4 shadow-lg shadow-red-100">
                    Log donor registration <i class="fas fa-heart text-sm"></i>
                </button>
            </form>
        </div>
    </div>

    <!-- Compatibility Modal -->
    <div id="compModal" class="fixed inset-0 bg-black/40 hidden items-center justify-center z-[100] modal-blur p-4">
        <div class="bg-white rounded-[2.5rem] max-w-xl w-full p-12 shadow-2xl relative">
            <button onclick="closeModal('compModal')"
                class="absolute top-8 right-8 text-gray-300 hover:text-gray-500"><i
                    class="fas fa-times text-xl"></i></button>
            <h3 class="text-2xl font-bold mb-10" id="compTitle">Compatibility</h3>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-10">
                <div
                    class="bg-medical p-8 rounded-[2rem] border border-red-50 min-h-[160px] flex flex-col justify-between">
                    <div class="mb-4 text-left">
                        <span class="text-red-600 text-[10px] font-black tracking-widest uppercase block mb-1">Can
                            Donate To</span>
                        <span class="text-gray-400 text-[11px] block">দান করতে পারে</span>
                    </div>
                    <div class="flex flex-wrap gap-2" id="donateToList"></div>
                </div>
                <div
                    class="bg-medical p-8 rounded-[2rem] border border-red-50 min-h-[160px] flex flex-col justify-between">
                    <div class="mb-4 text-left">
                        <span class="text-red-600 text-[10px] font-black tracking-widest uppercase block mb-1">Can
                            Receive From</span>
                        <span class="text-gray-400 text-[11px] block">গ্রহণ করতে পারে</span>
                    </div>
                    <div class="flex flex-wrap gap-2" id="receiveFromList"></div>
                </div>
            </div>
            <p class="text-gray-400 text-[10px] text-center font-medium leading-relaxed px-10">Always confirm
                compatibility with a medical professional before transfusion.</p>
        </div>
    </div>

    <!-- Emergency Blood Banks Modal -->
   <div id="emergencyModal" class="fixed inset-0 bg-black/40 hidden items-center justify-center z-[110] modal-blur p-4">
    <div class="bg-white rounded-[2.5rem] max-w-lg w-full p-10 shadow-2xl relative">
        <button onclick="closeModal('emergencyModal')" class="absolute top-8 right-8 text-gray-400 hover:text-gray-600 transition">
            <i class="fas fa-times text-xl"></i>
        </button>
        <h3 class="text-2xl font-bold text-gray-900 mb-8">Emergency blood banks</h3>
        
        <div class="space-y-4">
            @foreach($emergencyBanks as $bank)
                <div class="flex items-center justify-between p-5 border border-gray-100 rounded-[1.5rem] hover:bg-gray-50 transition text-left">
                    <div>
                        <h4 class="font-bold text-gray-900 text-base">{{ $bank->name }}</h4>
                        <p class="text-gray-400 text-sm mt-1">{{ $bank->phone }}</p>
                    </div>
                    <a href="tel:{{ $bank->phone }}"
                        class="bg-red-600 text-white px-6 py-2.5 rounded-full flex items-center gap-2 text-sm font-bold hover:bg-red-700 transition">
                        <i class="fas fa-phone-alt text-xs"></i> Call
                    </a>
                </div>
            @endforeach
        </div>
    </div>
</div>

    <script>
        // const donors = [{
        //         name: "Tanvir Hossain",
        //         group: "O+",
        //         district: "Dhaka",
        //         loc: "Mirpur, Dhaka",
        //         phone: "+8801711111111"
        //     },
        //     {
        //         name: "Sadia Akter",
        //         group: "A+",
        //         district: "Dhaka",
        //         loc: "Dhanmondi, Dhaka",
        //         phone: "+8801822222222"
        //     },
        //     {
        //         name: "Rakib Hasan",
        //         group: "B+",
        //         district: "Chattogram",
        //         loc: "GEC, Chattogram",
        //         phone: "+8801933333333"
        //     },
        //     {
        //         name: "Nusrat Jahan",
        //         group: "AB-",
        //         district: "Dhaka",
        //         loc: "Uttara, Dhaka",
        //         phone: "+8801644444444"
        //     },
        //     {
        //         name: "Mahmudul Karim",
        //         group: "O-",
        //         district: "Sylhet",
        //         loc: "Zindabazar, Sylhet",
        //         phone: "+8801555555555"
        //     },
        //     {
        //         name: "Farhana Rahman",
        //         group: "A-",
        //         district: "Chattogram",
        //         loc: "Agrabad, Chattogram",
        //         phone: "+8801366666666"
        //     }
        // ];

        const bloodData = {
            'A+': {
                bengali: 'এ পজিটিভ',
                donate: ['A+', 'AB+'],
                receive: ['A+', 'A-', 'O+', 'O-']
            },
            'A-': {
                bengali: 'এ নেগেটিভ',
                donate: ['A+', 'A-', 'AB+', 'AB-'],
                receive: ['A-', 'O-']
            },
            'B+': {
                bengali: 'বি পজিটিভ',
                donate: ['B+', 'AB+'],
                receive: ['B+', 'B-', 'O+', 'O-']
            },
            'B-': {
                bengali: 'বি নেগেটিভ',
                donate: ['B+', 'B-', 'AB+', 'AB-'],
                receive: ['B-', 'O-']
            },
            'O+': {
                bengali: 'ও পজিটিভ',
                donate: ['A+', 'B+', 'AB+', 'O+'],
                receive: ['O+', 'O-']
            },
            'O-': {
                bengali: 'ও নেগেটিভ',
                donate: ['All Groups'],
                receive: ['O-']
            },
            'AB+': {
                bengali: 'এবি পজিটিভ',
                donate: ['AB+'],
                receive: ['All Groups']
            },
            'AB-': {
                bengali: 'এবি নেগেটিভ',
                donate: ['AB+', 'AB-'],
                receive: ['A-', 'B-', 'O-', 'AB-']
            }
        };

        // ২. ডোনার কার্ড রেন্ডার করা
        function displayDonors(list) {
            const container = document.getElementById('donorContainer');
            const countText = document.getElementById('matchCount');
            container.innerHTML = '';
            countText.innerText = `${list.length} donors match your search.`;

            if (list.length === 0) {
                container.innerHTML = '<p class="col-span-full py-10 text-gray-400 text-center">No donors found.</p>';
                return;
            }

            list.forEach(d => {
                container.innerHTML += `
                    <div class="bg-white p-6 rounded-2xl border border-gray-100 flex items-center justify-between shadow-sm hover:shadow-md transition">
                        <div class="flex items-center gap-4 text-left">
                            <div class="bg-red-600 text-white w-12 h-12 rounded-full flex items-center justify-center font-bold text-sm">${d.group}</div>
                            <div>
                                <h4 class="font-bold text-gray-900">${d.name}</h4>
                                <p class="text-[11px] text-gray-400 font-medium flex items-center gap-1">
                                    <i class="fas fa-location-dot"></i> ${d.loc}
                                </p>
                            </div>
                        </div>
                        <a href="tel:${d.phone}" class="bg-red-600 text-white p-2.5 rounded-xl flex items-center gap-2 text-xs font-bold hover:bg-red-700">
                            <i class="fas fa-phone"></i> Call
                        </a>
                    </div>
                `;
            });
        }

        // ৩. ফিল্টার ফাংশন
        function filterDonors() {
            const group = document.getElementById('searchGroup').value;
            const district = document.getElementById('searchDistrict').value;

            const filtered = donors.filter(d => {
                const groupMatch = (group === "Any") || (d.group === group);
                const districtMatch = (district === "Any") || (d.district === district);
                return groupMatch && districtMatch;
            });

            displayDonors(filtered);
        }

        // ৪. ইউটিলিটি ফাংশন (Modals & Compatibility)
        function openModal(id) {
            document.getElementById(id).classList.replace('hidden', 'flex');
            document.body.style.overflow = 'hidden';
        }

        function closeModal(id) {
            document.getElementById(id).classList.replace('flex', 'hidden');
            document.body.style.overflow = 'auto';
        }

        function showComp(group) {
            const data = bloodData[group];
            document.getElementById('compTitle').innerText = `Compatibility — ${group} (${data.bengali})`;
            const badges = (list, isFill) => list.map(item =>
                `<span class="${isFill ? 'bg-red-600 text-white' : 'border border-red-600 text-red-600'} px-4 py-1.5 rounded-full text-[11px] font-bold min-w-[48px] text-center">${item}</span>`
            ).join('');
            document.getElementById('donateToList').innerHTML = badges(data.donate, true);
            document.getElementById('receiveFromList').innerHTML = badges(data.receive, false);
            openModal('compModal');
        }

        // গ্রিড জেনারেটর
        const grid = document.getElementById('bloodGrid');
        Object.keys(bloodData).forEach(group => {
            grid.innerHTML += `
                <div onclick="showComp('${group}')" class="bg-white border border-gray-100 rounded-[2rem] p-10 text-center hover:shadow-xl transition-all cursor-pointer group hover:-translate-y-1 relative overflow-hidden">
                    <div class="absolute top-4 right-6 text-red-500 opacity-20 group-hover:opacity-100 transition-opacity"><i class="fas fa-droplet text-xs"></i></div>
                    <h4 class="text-4xl font-black text-red-600 mb-2">${group}</h4>
                    <p class="text-[10px] text-gray-400 font-bold uppercase tracking-wider">View compatibility</p>
                </div>
            `;
        });

        window.onload = () => displayDonors(donors);
        window.onclick = e => {
            if (e.target.classList.contains('fixed')) closeModal(e.target.id);
        }
    </script>
</body>

</html>
